# Generated by Django 3.2.12 on 2022-11-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0004_auto_20221103_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='apiv1.Category'),
        ),
    ]
